package com.example.domain.model

enum class Nature {
    AQUA, BEAST, BEAST_WARRIOR, DINOSAUR, DRAGON, FAIRY, FIEND, FISH, INSECT, MACHINE, PLANT, PYRO,
    REPTILE, ROCK, SEA_SERPENT, SPELL_CASTER, THUNDER, WARRIOR, WINGED_BEAST, ZOMBIE, NONE
}